version: '3'

services:

  server:
    build: ./server
    container_name: 'server'
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    env_file: 
      - .env
    restart: always

  redis: 
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379

  redis-aof: 
    image: redis
    container_name: redis-aof
    ports:
      - 6380:6379
    volumes:
      - ./conf/redis-aof.conf:/usr/local/etc/redis/redis.conf      
    command: redis-server /usr/local/etc/redis/redis.conf --port 6380

  beanstalkd:
    image: evanskaufman/beanstalkd:latest
    container_name: beanstalkd
    ports:
      - 11300:11300
    restart: always

volumes:
  conf:

